#!/bin/bash

# Para listar os tipos de sistemas operacionais possiveis filtrando apenas o Red Hat, execute:
# VBoxManage list ostypes | grep RedHat

MEMORY_SIZE=${MEMORY_SIZE:-1024}
HD_SIZE=${HD_SIZE:-8192}
VM_BASEFOLDER=${VM_BASEFOLDER:-~/VirtualBox VMs}
VM_DIR=$VM_BASEFOLDER/vm-fedora

case `uname` in
  Darwin)
    FEDORA_ISO=${FEDORA_ISO:-~/Sites/Fedora/releases/20/Fedora/x86_64/iso/Fedora-20-x86_64-netinst.iso}
    VBOXGUESTADDITIONS_ISO=${VBOXGUESTADDITIONS_ISO:-/Applications/VirtualBox.app/Contents/MacOS/VBoxGuestAdditions.iso}
    ;;
  Linux)
    FEDORA_ISO=${FEDORA_ISO:-~/public_html/Fedora/releases/20/Fedora/x86_64/iso/Fedora-20-x86_64-netinst.iso}
    VBOXGUESTADDITIONS_ISO=${VBOXGUESTADDITIONS_ISO:-/usr/share/virtualbox/VBoxGuestAdditions.iso}
    ;;
  *)
    echo "Esse script ainda não está configurado para \"`uname`\"!"
    exit 1
    ;;
esac

VBoxManage createvm --name vm-fedora --ostype Fedora_64 --register
VBoxManage modifyvm vm-fedora --memory $MEMORY_SIZE --clipboard bidirectional --accelerate3d on
VBoxManage createhd --filename "$VM_DIR/vm-fedora.vdi" --size $HD_SIZE --format VDI
VBoxManage storagectl vm-fedora --name "SATA Controller" --add sata --controller IntelAhci
VBoxManage storageattach vm-fedora --storagectl "SATA Controller" --port 0 --device 0 --type hdd --medium "$VM_DIR/vm-fedora.vdi"
VBoxManage storagectl vm-fedora --name "IDE Controller" --add ide --controller PIIX4
VBoxManage storageattach vm-fedora --storagectl "IDE Controller" --port 1 --device 0 --type dvddrive --medium "$FEDORA_ISO"
VBoxManage storageattach vm-fedora --storagectl "IDE Controller" --port 1 --device 1 --type dvddrive --medium "$VBOXGUESTADDITIONS_ISO"
