#!/bin/bash
# Author: Paulo Jerônimo (@paulojeronimo, pj@paulojeronimo.info)

BASEDIR=`dirname "$0"`
source "$BASEDIR/functions"

for mirror in `find "$BASEDIR/.." -maxdepth 1 -type d ! -name '.*'`
do
   $BASEDIR/create-mirror-link.$mirror "$@"
done
