#!/bin/bash
# Author: Paulo Jerônimo (@paulojeronimo, pj@paulojeronimo.info)
set +x

BASEDIR=`dirname "$0"`
source "$BASEDIR/load-config"

LINK_TYPE="${1:-local}"; debug "LINK_TYPE=$LINK_TYPE"
link_is_local=true
[ "$LINK_TYPE" = "local" ] || link_is_local=false

cd "$BASEDIR/../$MIRROR_NAME"
rm -f mirror
os=`uname -s`
case $os in
  Darwin) 
    $link_is_local && \
      ln -s $LOCAL_MIRRORS_DIR_ON_DARWIN/$NAME mirror || \
      ln -s $EXTERNAL_MIRRORS_DIR_ON_DARWIN/$NAME mirror
    ;;
  Linux)
    $link_is_local && \
      ln -s $LOCAL_MIRRORS_DIR_ON_LINUX/$NAME mirror || \
      ln -s $EXTERNAL_MIRRORS_DIR_ON_LINUX/$NAME mirror
    ;;
  *) 
    echo "\"$os\" isn't supported!"
    exit 1
    ;;
esac
