#!/bin/bash
# Author: Paulo Jerônimo (@paulojeronimo, pj@paulojeronimo.info)

BASEDIR=`dirname "$0"`
source "$BASEDIR/functions"

cd "$BASEDIR"

for mirror in `find .. -maxdepth 1 -type d ! -name '.*'`
do
   mirror=`basename $mirror`
   ln -s create-mirror-link create-mirror-link.$mirror
   ./create-mirror-link.$mirror
   ln -s mirror-from-external-hd mirror-from-external-hd.$mirror
   ln -s mirror-to-external-hd mirror-to-external-hd.$mirror
   ln -s mirror-diff mirror-diff.$mirror
done
