#!/bin/bash
# Author: Paulo Jerônimo (@paulojeronimo, pj@paulojeronimo.info)
#
# This is a shared code (not executable alone) used by scripts in this directory

source "$BASEDIR/common"

configs="$BASEDIR/config $BASEDIR/config.sample"
found=false
for config in $configs
do
   [ -f "$config" ] && { source "$config"; found=true; break; }
done

if $found 
then
  debug "\"$config\" file loaded!"
else
  echo "No configuration file found!"
  exit 1
fi
