#!/bin/bash
# Author: Paulo Jeronimo (@paulojeronimo, pj@paulojeronimo.info)

BASEDIR=`dirname "$0"`
source "$BASEDIR/load-config"

os=`uname -s`
case $os in
  Darwin)
    EXTERNAL=$EXTERNAL_MIRRORS_DIR_ON_DARWIN
    LOCAL=$LOCAL_MIRRORS_DIR_ON_DARWIN
    ;;
  Linux)
    EXTERNAL=$EXTERNAL_MIRRORS_DIR_ON_LINUX
    LOCAL=$LOCAL_MIRRORS_DIR_ON_LINUX
    ;;
  *)
    echo "\"$os\" isn't supported!"
    exit 1
    ;;
esac

cd /tmp
rm -rf $MIRROR_NAME*

for d in $LOCAL $EXTERNAL
do
   rm -f $MIRROR_NAME
   ln -s $d/$MIRROR_NAME
   cd $MIRROR_NAME &> /dev/null
   find . -type f | sort > /tmp/$MIRROR_NAME`echo $d | sed 's,/,\.,g'`
   cd - &> /dev/null
done

vim -d $MIRROR_NAME.*
