#!/bin/bash
# Author: Paulo Jerônimo (@paulojeronimo, pj@paulojeronimo.info)

BASEDIR=`dirname "$0"`
source "$BASEDIR/load-config"

os=`uname -s`
case $os in
  Darwin)
    EXTERNAL_MIRRORS_DIR=$EXTERNAL_MIRRORS_DIR_ON_DARWIN
    LOCAL_MIRRORS_DIR=$LOCAL_MIRRORS_DIR_ON_DARWIN
    ;;
  Linux)
    EXTERNAL_MIRRORS_DIR=$EXTERNAL_MIRRORS_DIR_ON_LINUX
    LOCAL_MIRRORS_DIR=$LOCAL_MIRRORS_DIR_ON_LINUX
    ;;
  *)
    echo "\"$os\" isn't supported!"
    exit 1
    ;;
esac

rsync -av --update --delete \
"$EXTERNAL_MIRRORS_DIR/$NAME" \
"$LOCAL_MIRRORS_DIR"
