#!/bin/bash
# Author: Paulo Jerônimo (@paulojeronimo, pj@paulojeronimo.info)

BASEDIR=`dirname "$0"`
source "$BASEDIR/functions"

cd "$BASEDIR/.."

for mirror in `find . -maxdepth 1 -type d ! -name '.*'`
do
  for version in $mirror/*
  do
    for architecture in $version/*
    do
      rm -rf `basename $mirror`/`basename $version`/`basename $architecture`/mirror
    done
  done
done
