#!/bin/bash
# Author: Paulo Jerônimo (@paulojeronimo, pj@paulojeronimo.info)

BASEDIR=`dirname "$0"`
source "$BASEDIR/functions"

cd "$BASEDIR/.."

for mirror in `find . -maxdepth 1 -type d ! -name '.*'`
do
   rm -rf `basename $mirror`/mirror
done
