#!/bin/bash
# Author: Paulo Jerônimo (@paulojeronimo, pj@paulojeronimo.info)

BASEDIR=`dirname "$0"`
source "$BASEDIR/common"

cd ~/Sites

rm centos
rm ks

ln -s $PROJECTDIR/$MIRROR_NAME/mirror centos
ln -s $PROJECTDIR/$MIRROR_NAME/vm/ks.base ks
