#!/bin/bash
# Author: Paulo Jerônimo (@paulojeronimo, pj@paulojeronimo.info)

BASEDIR=`dirname "$0"`
source "$BASEDIR/common"

os=`uname -s`
case $os in
  Darwin)
    REMOTE_MIRRORS_DIR=${REMOTE_MIRRORS_DIR:-/Volumes/PJ-HFS/mirrors}
    ;;
  Linux)
    REMOTE_MIRRORS_DIR=${REMOTE_MIRRORS_DIR:-/run/media/pj/PJ-HFS/mirrors}
    ;;
  *)
    echo "\"$os\" isn't supported!"
    exit 1
    ;;
esac

d=$BASEDIR/../$MIRROR/$VERSION/$ARCHITECTURE/mirror
set -x
rsync -av --update --delete "$d/" "$REMOTE_MIRRORS_DIR/$NAME/"
set +x
