#!/bin/bash
# Author: Paulo Jerônimo (@paulojeronimo, pj@paulojeronimo.info)

BASEDIR=`dirname "$0"`
source "$BASEDIR/common"

os=`uname -s`
case $os in
  Darwin)
    EXTERNAL_HD_MIRRORS_DIR=${EXTERNAL_HD_MIRRORS_DIR:-/Volumes/PJ-HFS/mirrors}
    LOCAL_HD_MIRRORS_DIR=${LOCAL_HD_MIRRORS_DIR:-/Volumes/data/mirrors}
    ;;
  Linux)
    EXTERNAL_HD_MIRRORS_DIR=${EXTERNAL_HD_MIRRORS_DIR:-/run/media/pj/PJ-HFS/mirrors}
    LOCAL_HD_MIRRORS_DIR=${LOCAL_HD_MIRRORS_DIR:-/home/mirrors}
    ;;
  *)
    echo "\"$os\" isn't supported!"
    exit 1
    ;;
esac

set -x
rsync -av --update --delete $EXTERNAL_HD_MIRRORS_DIR/$NAME $LOCAL_HD_MIRRORS_DIR
set +x
