#!/bin/bash
# Author: Paulo Jerônimo (@paulojeronimo, pj@paulojeronimo.info)

BASEDIR=`dirname "$0"`
source "$BASEDIR/functions"

for mirror in $BASEDIR/../*
do
  for version in $mirror/*
  do
    for architecture in $version/*
    do
      debug "mirror=$mirror"
      debug "version=$version"
      debug "architecture=$architecture"
      rm -rf $BASEDIR/../`basename $mirror`/`basename $version`/`basename $architecture`/mirror
    done
  done
done
